spring.application.name=codeintel

spring.datasource.url=jdbc:postgresql://localhost:5432/codeintel
spring.datasource.username=myuser
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

codeintel.storage.repos-path=./data/repos
codeintel.parser.base-url=http://localhost:3001


codeintel.ollama.base-url=http://localhost:11434
codeintel.ollama.embedding-model=nomic-embed-text

codeintel.qdrant.base-url=http://localhost:6333
codeintel.qdrant.collection=code-chunks

codeintel.ollama.chat-model=qwen2.5-coder


