spring.application.name=codeintel

spring.datasource.url=jdbc:postgresql://localhost:5432/codeintel
spring.datasource.username=myuser
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

codeintel.storage.repos-path=./data/repos